### ISSUE TITLE
Check API with Bittrex team

### ISSUE THREAD

**Issue by yordis** [straw-hat-llc/elixir_bittrex#1]
Find the answer to those questions to be able to finish some tasks

## Tasks and Questions
- [x] 1. Is the `Id` and the `uuid ` the same on `getmarkethistory` and `buylimit`;`selllimit `?
- [x] 2. Is the `Rate` and the `Price` the same on `getorderbook` and `getmarkethistory`?
- [x] 3. What is the `TimeStamp` on `getmarkethistory`?
- [x] 4. What is `BaseVolume`, `TimeStamp`, `PrevDay` on `getmarketsummaries`
  - [x] Add those fields
- [x] 5. Is `limit orders` just an `order` or there is any differences?
- [x] 6. Ask for the list of `error` keys of the API
- [x] 7. Is message only being used when there is an error and/or `success` is `false`?
- [x] 8. Is an order always either `opened` or `closed` on `getopenorders`?
- [x] 9. Is `ConditionTarget` only present when `Condition` is present on `getopenorders`?
  - [x] Find examples of `Condition`
  - [x] Add those fields
- [x] 10. What is the API Rate Limit?

**Comment by bittrex-james** [comment]
1) No
2) Yes
3) The Timestamp of when the trade took place
4) Base Vol is based on the base currency of the pair
    TimeStamp is when the information was captured
   PrevDay is the prev day closing price
5) Its the only type of order supported by the API
6) Error keys?  Not sure what you're looking for here
7) Yes, if there is a failure, the error should be in the 'message' otherwise 'result' holds the return of a successful call
8) getOpenedOrders should only return you open orders... otherwise the name wouldn't make sense :)
9) No, it will always be there
    If IsConditional is True, check the condition.  NONE, GreaterThan, LessThan
10) Its dynamic, pick a reasonable polling rate based on your needs.  The more aggressive you are the more likely you are to get banned.  Look into using the Websocket for push info for trade and market activity

**Comment by yordis** [comment]
> 1. No

@bittrex-james what are they then?

> 6. Error keys? Not sure what you're looking for here

@bittrex-james The `message` key normally give me some error like this one `INVALID_ORDER` so I am assuming that you have a set of error message keys rather than human text. So I would like to have that list.

> 8. getOpenedOrders should only return you open orders... otherwise the name wouldn't make sense :)

@bittrex-james I got that, but the reason I am asking is because I can assume that either it's `opened` or it's `closed` so one of them will be `null` all the time. If so I can transform that to `status` field which have `name` and `at` which represent the data structure for that information rather than just let the user deal with `opened` and `created`.

> 5. Its the only type of order supported by the API

@bittrex-james but do you have that implemented? I could write the client a little bit smart and knows that there is a different and create more than one data structure, just preparing if you decide to open the API to `orders`. With a simple study I can be prepare and don't shoot myself on the foot. 

> 10. Its dynamic, pick a reasonable polling rate based on your needs. The more aggressive you are the more likely you are to get banned. Look into using the Websocket for push info for trade and market activity

@bittrex-james where can I find about the `websocket` piece? Also, what is a reasonable polling rate? Right now I need high frequency trading so for me it's really high the needs.

> 4. TimeStamp is when the information was captured

@bittrex-james what is the differences between `TimeStamp` and `

**Comment by bittrex-james** [comment]
1. UUID from a Selllimit/buylimit is what you would you to pass to GetOrder to get the details of that specific order.  The ID in getMarketHistory is just information for events occurring in that market 
6. I don't currently know these
8. In calling getOpenOrders, closed should always be null or it wouldn't show up in this list.
5. At this time this is all we currently support for orders
10. Look in the Api-developers channel.  There is a pinned document outlining the use of the websocket.  Look at this first to see if you can leverage it before guessing on a polling rate.
4.  Created is when the market first appeared on the exchange, where as timestamp relates to when the client was provided the information

**Comment by bittrex-james** [comment]
1 UUID from a Selllimit/buylimit is what you would you to pass to GetOrder to get the details of that specific order.  The ID in getMarketHistory is just information for events occurring in that market 

6 I don't currently know these

8 In calling getOpenOrders, closed should always be null or it wouldn't show up in this list.

5 At this time this is all we currently support for orders

10 Look in the Api-developers channel.  There is a pinned document outlining the use of the websocket.  Look at this first to see if you can leverage it before guessing on a polling rate.

4 Created is when the market first appeared on the exchange, where as timestamp relates to when the client was provided the information

**Comment by yordis** [comment]
> 8 In calling getOpenOrders, closed should always be null or it wouldn't show up in this list.

I got that, but I am not just mapping whatever is in the API I am trying to understand how the data structures of the API work. I understand that `closed` should always be `null` on this API call

> 5 At this time this is all we currently support for orders

I dont think you understood what I am trying to say

cc: @bittrex-james

**Comment by bittrex-james** [comment]
It sounds like you want to know what we plan to release, but I can't speak to that... Things can change all the way up till we release, so speculating could just cause undue work.

**Comment by yordis** [comment]
> The ID in getMarketHistory is just information for events occurring in that market

@bittrex-james what do you mean?

**Comment by bittrex-james** [comment]
The BuyLimit/SellLimit UUID corresponds to a specific order for the user, whereas the ID in GetMarketHistory is just an ID for the orderbook of the market you got history on.  So they don't relate to each other at all.
